### ISSUE TITLE
Possibility to disable media cloning

### ISSUE THREAD

**Issue by idflood** [mcguffin/polylang-fix-relationships#3]
On some sites I prefer to disable the media translation in polylang. But even if this setting is disabled this plugin still duplicate all images and attachments.

It would be great if this plugin could check if media translation is enabled or at least provide a way to configure it.

**Comment by mcguffin** [comment]
Just tried to reproduce the issue in WP 4.5.2 + Polylang 1.9. Everything went well – no image duplication with media translations disabled. Could have been the polylang update...
